# Generated by Django 5.0.3 on 2024-03-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoe_items", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
