# Generated by Django 5.0.3 on 2024-03-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoe_items", "0004_alter_orderitem_price_sales_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="brands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brands",
                    models.CharField(
                        choices=[
                            ("jordan", "jordan"),
                            ("nike", "nike"),
                            ("puma", "puma"),
                            ("adidas", "adidas"),
                            ("new_balance", "new_balance"),
                            ("reebok", "reebok"),
                            ("vans", "vans"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="sub_image",
            options={"verbose_name_plural": "Sub images"},
        ),
        migrations.AddField(
            model_name="sales_stats",
            name="brand_ordered",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.CharField(
                choices=[
                    ("trending", "trending"),
                    ("outdoor", "outdoor"),
                    ("discounted", "discounted"),
                    ("vintage", "vintage"),
                    ("new", "new"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brands",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shoe_items.brands"
            ),
        ),
    ]
