# Generated by Django 5.0.3 on 2024-03-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoe_items", "0005_brands_alter_sub_image_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brands",
            field=models.CharField(
                choices=[
                    ("jordan", "jordan"),
                    ("nike", "nike"),
                    ("puma", "puma"),
                    ("adidas", "adidas"),
                    ("new_balance", "new_balance"),
                    ("reebok", "reebok"),
                    ("vans", "vans"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="brands",
        ),
    ]
